import { useMemo } from 'react';
import { useDocsSidebar } from '@docusaurus/plugin-content-docs/client';
import { upcomingModules } from './tutorialData';
import { isPageComplete, useTutorialProgress } from './TutorialProgressContext';

/**
 * Derives the tracker's view of the tutorial from the generated sidebar plus stored progress.
 *
 * Top-level sidebar categories are modules and their doc links are pages. Because the sidebar
 * is autogenerated from the folder structure, adding a page to the tutorial needs no change
 * here, and a page can never be missing from the tracker.
 *
 * Sidebar item labels are the page titles: the tutorial pages deliberately set no
 * `sidebar_label`, and Docusaurus falls back to `title`.
 *
 * Totals are derived, never persisted, so restructuring the tutorial cannot leave stored
 * progress inconsistent.
 */
export function useTutorialOutline(currentPageId) {
  const { hydrated, pages } = useTutorialProgress();
  const sidebar = useDocsSidebar();

  return useMemo(() => {
    const written = (sidebar?.items ?? [])
      // Start from root "Tutorial" category (used for breadcrumbs, see sidebarsTutorial.js)
      .find((item) => item.type === 'category' && item.label === 'Tutorial')?.items
      .filter((item) => item.type === 'category')
      .map((category) => {
        const modulePages = category.items
          .filter((item) => item.type === 'link' && item.docId)
          .map((item) => ({
            id: item.docId,
            title: item.label,
            // Sidebar hrefs already include baseUrl, so they are used as-is.
            permalink: item.href,
            done: isPageComplete(pages, item.docId),
            isCurrent: item.docId === currentPageId,
          }));

        return {
          // First segment of a page id is the module folder — stable, unlike the label.
          id: modulePages[0]?.id.split('/')[0] ?? category.label,
          label: category.label,
          upcoming: false,
          permalink: modulePages[0]?.permalink,
          pages: modulePages,
          total: modulePages.length,
          done: modulePages.filter((p) => p.done).length,
          isCurrent: modulePages.some((p) => p.isCurrent),
        };
      })
      // A module with no pages would be an empty category; nothing to show.
      .filter((module) => module.total > 0);

    const planned = upcomingModules.map((module) => ({
      ...module,
      upcoming: true,
      permalink: undefined,
      pages: [],
      total: 0,
      done: 0,
      isCurrent: false,
    }));

    const totalPages = written.reduce((sum, m) => sum + m.total, 0);
    const totalDone = written.reduce((sum, m) => sum + m.done, 0);

    return {
      hydrated,
      modules: [...written, ...planned],
      currentModule: written.find((m) => m.isCurrent) ?? null,
      totalPages,
      totalDone,
      percent: totalPages === 0 ? 0 : Math.round((totalDone / totalPages) * 100),
    };
  }, [hydrated, pages, currentPageId, sidebar]);
}
