/**
 * Sidebar for the follow-along tutorial (docs plugin instance "tutorial", served at /tutorial).
 *
 * Fully autogenerated from the folder structure. Ordering comes from the number prefixes on
 * folders and files (`2-testing-our-module/1-setup.mdx`), which Docusaurus strips from both
 * the doc id and the URL — so the order lives next to the content and adding a page needs no
 * edit here. Module labels come from each folder's _category_.json.
 *
 * The progress tracker reads this same generated sidebar at runtime, so it stays in sync
 * automatically. See src/tutorial/useTutorialOutline.js.
 *
 * Note: do not give these categories a `link: {type: 'generated-index'}`. Generated index
 * pages are not rendered through @theme/DocItem, so they would not show the tracker.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  tutorial: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};
