/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Powershell.Docusaurus.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'commands/Add-AssertionOperator',
    'commands/AfterAll',
    'commands/AfterEach',
    'commands/AfterEachFeature',
    'commands/AfterEachScenario',
    'commands/Assert-MockCalled',
    'commands/Assert-VerifiableMock',
    'commands/Assert-VerifiableMocks',
    'commands/BeforeAll',
    'commands/BeforeEach',
    'commands/BeforeEachFeature',
    'commands/BeforeEachScenario',
    'commands/Context',
    'commands/Describe',
    'commands/Find-GherkinStep',
    'commands/Get-ShouldOperator',
    'commands/Get-TestDriveItem',
    'commands/GherkinStep',
    'commands/In',
    'commands/InModuleScope',
    'commands/Invoke-Gherkin',
    'commands/Invoke-Pester',
    'commands/It',
    'commands/Mock',
    'commands/New-Fixture',
    'commands/New-MockObject',
    'commands/New-PesterOption',
    'commands/Set-ItResult',
    'commands/Set-TestInconclusive',
    'commands/Setup',
    'commands/Should'
];
