/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell 1.0.36.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'commands/Add-ShouldOperator',
    'commands/AfterAll',
    'commands/AfterEach',
    'commands/Assert-MockCalled',
    'commands/Assert-VerifiableMock',
    'commands/BeforeAll',
    'commands/BeforeDiscovery',
    'commands/BeforeEach',
    'commands/Context',
    'commands/ConvertTo-JUnitReport',
    'commands/ConvertTo-NUnitReport',
    'commands/ConvertTo-Pester4Result',
    'commands/Describe',
    'commands/Export-JUnitReport',
    'commands/Export-NUnitReport',
    'commands/Get-ShouldOperator',
    'commands/InModuleScope',
    'commands/Invoke-Pester',
    'commands/It',
    'commands/Mock',
    'commands/New-Fixture',
    'commands/New-MockObject',
    'commands/New-PesterConfiguration',
    'commands/New-PesterContainer',
    'commands/Set-ItResult',
    'commands/Should'
];
